# Generated by Django 4.2.16 on 2024-10-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hook_text',
        ),
    ]
