# Generated by Django 4.2.16 on 2024-11-18 07:27

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_product_content_remove_product_file_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('like', models.IntegerField()),
                
            ],
        ),
    ]
