# Generated by Django 4.2.16 on 2024-11-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
