# Generated by Django 4.2.16 on 2024-11-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='google_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
