# Generated by Django 4.2.16 on 2024-11-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_product_google_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='google_image_url',
        ),
    ]
