# Generated by Django 4.2.16 on 2024-12-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_product_google_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keyword',
        ),
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='durability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dislike',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
