# Generated by Django 4.2.16 on 2024-12-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_product_created_at_remove_product_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dislike',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='finish',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.FloatField(null=True),
        ),
    ]
